-- ============================================================================
--  AURORA  |  Sistema de comercio electronico multisucursal de ropa femenina
--  Materia: SI2  -  Parcial 1
--  Motor  : PostgreSQL 16
-- ============================================================================
--  GENERADO por scripts/mysql-a-postgres.mjs a partir de schema.mysql.sql.
--  No editar a mano: editar el origen o el script y volver a generar.
-- ============================================================================

SET client_min_messages = WARNING;


-- ============================================================================
-- 0. FUNCION DE APOYO: refresco automatico de actualizado_en
-- ============================================================================

CREATE OR REPLACE FUNCTION set_actualizado_en() RETURNS trigger AS $func$
BEGIN
  NEW.actualizado_en = now();
  RETURN NEW;
END;
$func$ LANGUAGE plpgsql;

-- ============================================================================
-- 1. TIPOS ENUMERADOS (39)
-- ============================================================================

CREATE TYPE almacen_tipo AS ENUM ('venta','deposito','devoluciones','transito');
CREATE TYPE dispositivo_plataforma AS ENUM ('web','android','ios');
CREATE TYPE cliente_tipo AS ENUM ('minorista','mayorista');
CREATE TYPE medida_cliente_origen AS ENUM ('manual','estimado','escaneo_camara');
CREATE TYPE talla_tipo AS ENUM ('alfa','numerica','calzado','unica');
CREATE TYPE producto_temporada AS ENUM ('verano','invierno','otono','primavera','todo_ano');
CREATE TYPE producto_tipo_prenda AS ENUM ('superior','inferior','vestido','abrigo','calzado','accesorio','ropa_interior');
CREATE TYPE movimiento_inventario_tipo AS ENUM ('entrada','salida','ajuste','transferencia_salida', 'transferencia_entrada','devolucion','reserva','liberacion');
CREATE TYPE transferencia_estado AS ENUM ('borrador','solicitada','aprobada','en_transito','recibida','rechazada');
CREATE TYPE compra_estado AS ENUM ('borrador','confirmada','recibida','anulada');
CREATE TYPE campania_tipo AS ENUM ('temporada','liquidacion','lanzamiento','black_friday','cierre');
CREATE TYPE promocion_tipo AS ENUM ('porcentaje','monto_fijo','2x1','envio_gratis');
CREATE TYPE promocion_aplica_a AS ENUM ('todo','categoria','producto','variante');
CREATE TYPE promocion_canal AS ENUM ('todos','online','tienda');
CREATE TYPE promocion_modalidad AS ENUM ('todas','menudeo','mayoreo');
CREATE TYPE pedido_canal AS ENUM ('online','tienda');
CREATE TYPE pedido_modalidad AS ENUM ('menudeo','mayoreo');
CREATE TYPE pedido_tipo_entrega AS ENUM ('inmediata','recojo_tienda','domicilio');
CREATE TYPE pedido_estado AS ENUM ('pendiente','pagado','preparando','listo','enviado', 'entregado','cancelado','devuelto');
CREATE TYPE metodo_pago_tipo AS ENUM ('efectivo','qr','tarjeta','transferencia','contra_entrega');
CREATE TYPE metodo_pago_canal AS ENUM ('todos','online','tienda');
CREATE TYPE pago_estado AS ENUM ('pendiente','confirmado','rechazado','reembolsado');
CREATE TYPE caja_estado AS ENUM ('abierta','cerrada');
CREATE TYPE movimiento_caja_tipo AS ENUM ('ingreso','egreso');
CREATE TYPE envio_estado AS ENUM ('preparando','en_ruta','entregado','fallido','devuelto');
CREATE TYPE devolucion_motivo AS ENUM ('talla_incorrecta','defecto','no_coincide','arrepentimiento','otro');
CREATE TYPE devolucion_estado AS ENUM ('solicitada','aprobada','rechazada','recibida','reembolsada');
CREATE TYPE devolucion_detalle_estado_prenda AS ENUM ('nueva','usada','danada');
CREATE TYPE avatar_tipo_cuerpo AS ENUM ('reloj_arena','triangulo','triangulo_invertido','rectangulo','ovalado');
CREATE TYPE prueba_virtual_modo AS ENUM ('avatar','ra_camara');
CREATE TYPE resena_ajuste_real AS ENUM ('pequena','justa','grande');
CREATE TYPE conversacion_canal AS ENUM ('web','movil','pos');
CREATE TYPE conversacion_tipo AS ENUM ('asistente_compra','reporte','soporte');
CREATE TYPE mensaje_rol AS ENUM ('usuario','asistente','sistema','herramienta');
CREATE TYPE plantilla_reporte_visual_default AS ENUM ('tabla','barras','lineas','torta','tarjeta');
CREATE TYPE consulta_reporte_entrada AS ENUM ('texto','voz');
CREATE TYPE sync_operacion_operacion AS ENUM ('crear','actualizar','eliminar');
CREATE TYPE sync_operacion_estado AS ENUM ('pendiente','aplicado','conflicto','rechazado');
CREATE TYPE notificacion_tipo AS ENUM ('pedido','stock','promocion','sistema','devolucion');

-- ============================================================================
-- 2. TABLAS (54)
-- ============================================================================

CREATE TABLE departamento (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(60) NOT NULL UNIQUE,
  pais VARCHAR(60) NOT NULL DEFAULT 'Bolivia',
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE ciudad (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  departamento_id INT NOT NULL,
  nombre VARCHAR(80) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_ciudad UNIQUE (departamento_id, nombre)
);

CREATE TABLE sucursal (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(20) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  ciudad_id INT NOT NULL,
  direccion VARCHAR(200) NOT NULL,
  latitud DECIMAL(10,7) NULL,
  longitud DECIMAL(10,7) NULL,
  telefono VARCHAR(30) NULL,
  email VARCHAR(120) NULL,
  horario VARCHAR(120) NULL,
  -- es_virtual = centro de distribucion que solo atiende pedidos online
  es_virtual BOOLEAN NOT NULL DEFAULT FALSE,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE almacen (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sucursal_id INT NOT NULL,
  codigo VARCHAR(20) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  tipo almacen_tipo NOT NULL DEFAULT 'venta',
  -- el almacen principal es el que descuenta stock en una venta de mostrador
  es_principal BOOLEAN NOT NULL DEFAULT FALSE,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE rol (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL UNIQUE,
  descripcion VARCHAR(200) NULL,
  -- los roles del sistema no se pueden borrar desde la UI
  es_sistema BOOLEAN NOT NULL DEFAULT FALSE,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE permiso (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(80) NOT NULL UNIQUE,   -- ej: producto.crear
  modulo VARCHAR(50) NOT NULL,          -- ej: producto
  descripcion VARCHAR(200) NULL
);

CREATE TABLE rol_permiso (
  rol_id INT NOT NULL,
  permiso_id INT NOT NULL,
  PRIMARY KEY (rol_id, permiso_id)
);

CREATE TABLE usuario (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rol_id INT NOT NULL,
  -- un vendedor/almacenero pertenece a una sucursal; un cliente no
  sucursal_id INT NULL,
  nombre VARCHAR(80) NOT NULL,
  apellido VARCHAR(80) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  telefono VARCHAR(30) NULL,
  ci VARCHAR(20) NULL,
  password_hash VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(255) NULL,
  email_verificado BOOLEAN NOT NULL DEFAULT FALSE,
  intentos_fallidos SMALLINT NOT NULL DEFAULT 0,
  bloqueado_hasta TIMESTAMPTZ NULL,
  ultimo_acceso TIMESTAMPTZ NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE dispositivo (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INT NULL,
  uuid VARCHAR(64) NOT NULL UNIQUE,
  plataforma dispositivo_plataforma NOT NULL,
  modelo VARCHAR(80) NULL,
  push_token VARCHAR(255) NULL,
  ultima_sync TIMESTAMPTZ NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE sesion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INT NOT NULL,
  dispositivo_id INT NULL,
  -- se guarda el hash del refresh token, nunca el token en claro
  token_hash VARCHAR(64) NOT NULL UNIQUE,
  ip VARCHAR(45) NULL,
  user_agent VARCHAR(255) NULL,
  expira_en TIMESTAMPTZ NOT NULL,
  revocado BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE bitacora (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INT NULL,
  accion VARCHAR(40) NOT NULL,   -- login, crear, actualizar, eliminar, exportar
  modulo VARCHAR(50) NOT NULL,
  entidad VARCHAR(60) NULL,
  entidad_id VARCHAR(40) NULL,
  descripcion VARCHAR(255) NULL,
  datos_previos JSONB NULL,
  datos_nuevos JSONB NULL,
  ip VARCHAR(45) NULL,
  user_agent VARCHAR(255) NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE cliente (
  usuario_id INT PRIMARY KEY,
  tipo cliente_tipo NOT NULL DEFAULT 'minorista',
  nit VARCHAR(20) NULL,
  razon_social VARCHAR(150) NULL,
  -- solo aplica a mayoristas; se valida antes de habilitar precios de mayoreo
  mayorista_aprobado BOOLEAN NOT NULL DEFAULT FALSE,
  descuento_extra DECIMAL(5,2) NOT NULL DEFAULT 0,
  limite_credito DECIMAL(12,2) NOT NULL DEFAULT 0,
  fecha_nacimiento DATE NULL,
  puntos INT NOT NULL DEFAULT 0
);

CREATE TABLE direccion_cliente (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id INT NOT NULL,
  alias VARCHAR(50) NOT NULL,      -- Casa, Oficina
  ciudad_id INT NOT NULL,
  direccion VARCHAR(200) NOT NULL,
  referencia VARCHAR(200) NULL,
  latitud DECIMAL(10,7) NULL,
  longitud DECIMAL(10,7) NULL,
  destinatario VARCHAR(120) NULL,
  telefono VARCHAR(30) NULL,
  es_principal BOOLEAN NOT NULL DEFAULT FALSE,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE medida_cliente (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id INT NOT NULL,
  altura_cm DECIMAL(5,1) NOT NULL,
  peso_kg DECIMAL(5,1) NOT NULL,
  busto_cm DECIMAL(5,1) NULL,
  cintura_cm DECIMAL(5,1) NULL,
  cadera_cm DECIMAL(5,1) NULL,
  entrepierna_cm DECIMAL(5,1) NULL,
  hombro_cm DECIMAL(5,1) NULL,
  -- si el cliente solo dio altura y peso, el resto se estima y se marca aqui
  origen medida_cliente_origen NOT NULL DEFAULT 'manual',
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_medida_cliente UNIQUE (cliente_id)
);

CREATE TABLE categoria (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  padre_id INT NULL,                       -- jerarquia: Ropa > Vestidos > Casual
  nombre VARCHAR(80) NOT NULL,
  slug VARCHAR(90) NOT NULL UNIQUE,
  imagen VARCHAR(255) NULL,
  orden INT NOT NULL DEFAULT 0,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE marca (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL UNIQUE,
  slug VARCHAR(90) NOT NULL UNIQUE,
  logo VARCHAR(255) NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE talla (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(10) NOT NULL,             -- XS, S, M, L / 36, 38, 40
  tipo talla_tipo NOT NULL DEFAULT 'alfa',
  orden INT NOT NULL DEFAULT 0,
  CONSTRAINT uq_talla UNIQUE (nombre, tipo)
);

CREATE TABLE color (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(40) NOT NULL UNIQUE,
  hex VARCHAR(7) NOT NULL                  -- #RRGGBB, se usa en el render del probador
);

CREATE TABLE producto (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_id INT NOT NULL,
  marca_id INT NULL,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(150) NOT NULL,
  slug VARCHAR(170) NOT NULL UNIQUE,
  descripcion TEXT NULL,
  material VARCHAR(120) NULL,
  cuidados VARCHAR(255) NULL,
  temporada producto_temporada NOT NULL DEFAULT 'todo_ano',
  tipo_prenda producto_tipo_prenda NOT NULL,
  destacado BOOLEAN NOT NULL DEFAULT FALSE,
  -- ranking simple para el buscador y el asistente IA
  vendidos INT NOT NULL DEFAULT 0,
  calificacion DECIMAL(3,2) NOT NULL DEFAULT 0,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now()
  -- busqueda por texto libre del catalogo y del asistente IA
);

CREATE TABLE producto_imagen (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id INT NOT NULL,
  color_id INT NULL,                    -- la galeria cambia segun el color elegido
  url VARCHAR(255) NOT NULL,
  alt VARCHAR(150) NULL,
  orden INT NOT NULL DEFAULT 0,
  es_principal BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE producto_prenda_3d (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id INT NOT NULL,
  color_id INT NULL,
  url_glb VARCHAR(255) NULL,          -- malla para el avatar 3D
  url_textura VARCHAR(255) NULL,          -- PNG con alpha para el overlay de RA
  -- puntos de anclaje sobre el esqueleto detectado por la camara
  anclaje_json JSONB NULL,
  escala_base DECIMAL(6,3) NOT NULL DEFAULT 1.000,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE variante (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id INT NOT NULL,
  talla_id INT NOT NULL,
  color_id INT NOT NULL,
  sku VARCHAR(40) NOT NULL UNIQUE,
  codigo_barras VARCHAR(40) NULL UNIQUE,
  precio_menor DECIMAL(12,2) NOT NULL,
  precio_mayor DECIMAL(12,2) NOT NULL,
  costo DECIMAL(12,2) NOT NULL DEFAULT 0,
  peso_gr INT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_variante UNIQUE (producto_id, talla_id, color_id)
);

CREATE TABLE escala_precio (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variante_id INT NOT NULL,
  cantidad_min INT NOT NULL,
  precio_unitario DECIMAL(12,2) NOT NULL,
  CONSTRAINT uq_escala UNIQUE (variante_id, cantidad_min)
);

CREATE TABLE guia_talla (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_id INT NOT NULL,
  talla_id INT NOT NULL,
  busto_min DECIMAL(5,1) NULL, busto_max DECIMAL(5,1) NULL,
  cintura_min DECIMAL(5,1) NULL, cintura_max DECIMAL(5,1) NULL,
  cadera_min DECIMAL(5,1) NULL, cadera_max DECIMAL(5,1) NULL,
  altura_min DECIMAL(5,1) NULL, altura_max DECIMAL(5,1) NULL,
  CONSTRAINT uq_guia UNIQUE (categoria_id, talla_id)
);

CREATE TABLE inventario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variante_id INT NOT NULL,
  almacen_id INT NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  -- reservado por pedidos online aun no despachados
  stock_reservado INT NOT NULL DEFAULT 0,
  stock_minimo INT NOT NULL DEFAULT 0,
  ubicacion VARCHAR(40) NULL,          -- pasillo/estante
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_inventario UNIQUE (variante_id, almacen_id),
  CONSTRAINT ck_inv_stock CHECK (stock >= 0 AND stock_reservado >= 0)
);

CREATE TABLE movimiento_inventario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variante_id INT NOT NULL,
  almacen_id INT NOT NULL,
  tipo movimiento_inventario_tipo NOT NULL,
  cantidad INT NOT NULL,            -- siempre positiva; el `tipo` da el signo
  stock_resultante INT NOT NULL,
  referencia_tipo VARCHAR(30) NULL,        -- pedido, compra, transferencia, devolucion
  referencia_id BIGINT NULL,
  usuario_id INT NULL,
  motivo VARCHAR(200) NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE transferencia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero VARCHAR(20) NOT NULL UNIQUE,
  almacen_origen_id INT NOT NULL,
  almacen_destino_id INT NOT NULL,
  estado transferencia_estado NOT NULL DEFAULT 'solicitada',
  usuario_solicita_id INT NOT NULL,
  usuario_aprueba_id INT NULL,
  observacion VARCHAR(255) NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  recibido_en TIMESTAMPTZ NULL
);

CREATE TABLE transferencia_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transferencia_id BIGINT NOT NULL,
  variante_id INT NOT NULL,
  cantidad INT NOT NULL,
  cantidad_recibida INT NOT NULL DEFAULT 0
);

CREATE TABLE proveedor (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  nit VARCHAR(20) NULL,
  contacto VARCHAR(120) NULL,
  telefono VARCHAR(30) NULL,
  email VARCHAR(120) NULL,
  direccion VARCHAR(200) NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE compra (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero VARCHAR(20) NOT NULL UNIQUE,
  proveedor_id INT NOT NULL,
  almacen_id INT NOT NULL,
  usuario_id INT NOT NULL,
  fecha DATE NOT NULL,
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  descuento DECIMAL(12,2) NOT NULL DEFAULT 0,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  estado compra_estado NOT NULL DEFAULT 'borrador',
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE compra_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_id BIGINT NOT NULL,
  variante_id INT NOT NULL,
  cantidad INT NOT NULL,
  costo_unitario DECIMAL(12,2) NOT NULL,
  subtotal DECIMAL(12,2) NOT NULL
);

CREATE TABLE campania (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  descripcion VARCHAR(255) NULL,
  tipo campania_tipo NOT NULL,
  banner_url VARCHAR(255) NULL,
  fecha_inicio TIMESTAMPTZ NOT NULL,
  fecha_fin TIMESTAMPTZ NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE promocion (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campania_id INT NULL,
  nombre VARCHAR(120) NOT NULL,
  tipo promocion_tipo NOT NULL,
  valor DECIMAL(12,2) NOT NULL DEFAULT 0,
  codigo_cupon VARCHAR(30) NULL UNIQUE,
  min_compra DECIMAL(12,2) NOT NULL DEFAULT 0,
  aplica_a promocion_aplica_a NOT NULL DEFAULT 'todo',
  aplica_id INT NULL,
  -- limita la promo a un canal o modalidad (ej: solo mayoreo, solo online)
  canal promocion_canal NOT NULL DEFAULT 'todos',
  modalidad promocion_modalidad NOT NULL DEFAULT 'todas',
  usos_max INT NULL,
  usos_actuales INT NOT NULL DEFAULT 0,
  fecha_inicio TIMESTAMPTZ NOT NULL,
  fecha_fin TIMESTAMPTZ NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE carrito (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id INT NULL,                  -- NULL = invitado
  session_token VARCHAR(64) NOT NULL UNIQUE,  -- permite carrito anonimo y offline
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE carrito_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  carrito_id BIGINT NOT NULL,
  variante_id INT NOT NULL,
  cantidad INT NOT NULL DEFAULT 1,
  precio_unitario DECIMAL(12,2) NOT NULL,
  agregado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_carrito_item UNIQUE (carrito_id, variante_id)
);

CREATE TABLE pedido (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero VARCHAR(20) NOT NULL UNIQUE,
  cliente_id INT NULL,               -- NULL en venta de mostrador sin registro
  sucursal_id INT NOT NULL,
  almacen_id INT NOT NULL,           -- de donde sale la mercaderia
  vendedor_id INT NULL,               -- usuario que atendio (venta en tienda)
  canal pedido_canal NOT NULL,
  modalidad pedido_modalidad NOT NULL DEFAULT 'menudeo',
  tipo_entrega pedido_tipo_entrega NOT NULL DEFAULT 'inmediata',
  estado pedido_estado NOT NULL DEFAULT 'pendiente',
  direccion_id INT NULL,
  promocion_id INT NULL,
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  descuento DECIMAL(12,2) NOT NULL DEFAULT 0,
  costo_envio DECIMAL(12,2) NOT NULL DEFAULT 0,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  moneda VARCHAR(3) NOT NULL DEFAULT 'BOB',
  nota VARCHAR(255) NULL,
  -- Sincronizacion offline: la clave la genera el cliente y el servidor la usa
  -- para que un mismo pedido reenviado no se registre dos veces.
  idempotency_key VARCHAR(36) NULL UNIQUE,
  creado_offline BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en_cliente TIMESTAMPTZ NULL,          -- hora real en que se hizo la venta sin red
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE pedido_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL,
  variante_id INT NOT NULL,
  -- se congela la descripcion por si el producto cambia de nombre despues
  descripcion VARCHAR(200) NOT NULL,
  cantidad INT NOT NULL,
  precio_unitario DECIMAL(12,2) NOT NULL,
  descuento DECIMAL(12,2) NOT NULL DEFAULT 0,
  subtotal DECIMAL(12,2) NOT NULL
);

CREATE TABLE pedido_historial (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL,
  estado VARCHAR(20) NOT NULL,
  usuario_id INT NULL,
  comentario VARCHAR(255) NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE metodo_pago (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(60) NOT NULL,
  tipo metodo_pago_tipo NOT NULL,
  requiere_comprobante BOOLEAN NOT NULL DEFAULT FALSE,
  -- si es 0, el metodo no se ofrece cuando el dispositivo esta sin red
  disponible_offline BOOLEAN NOT NULL DEFAULT FALSE,
  canal metodo_pago_canal NOT NULL DEFAULT 'todos',
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE pago (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL,
  metodo_pago_id INT NOT NULL,
  monto DECIMAL(12,2) NOT NULL,
  moneda VARCHAR(3) NOT NULL DEFAULT 'BOB',
  estado pago_estado NOT NULL DEFAULT 'pendiente',
  referencia_externa VARCHAR(120) NULL,      -- id de transaccion de la pasarela
  qr_payload TEXT NULL,              -- cadena EMV del QR generado
  comprobante_url VARCHAR(255) NULL,
  usuario_confirma_id INT NULL,
  idempotency_key VARCHAR(36) NULL UNIQUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  confirmado_en TIMESTAMPTZ NULL
);

CREATE TABLE caja (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sucursal_id INT NOT NULL,
  usuario_id INT NOT NULL,
  monto_apertura DECIMAL(12,2) NOT NULL DEFAULT 0,
  monto_cierre DECIMAL(12,2) NULL,
  monto_esperado DECIMAL(12,2) NULL,
  diferencia DECIMAL(12,2) NULL,
  estado caja_estado NOT NULL DEFAULT 'abierta',
  abierta_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  cerrada_en TIMESTAMPTZ NULL
);

CREATE TABLE movimiento_caja (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caja_id BIGINT NOT NULL,
  tipo movimiento_caja_tipo NOT NULL,
  monto DECIMAL(12,2) NOT NULL,
  concepto VARCHAR(150) NOT NULL,
  pago_id BIGINT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE envio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL UNIQUE,
  direccion_id INT NULL,
  repartidor_id INT NULL,
  empresa VARCHAR(80) NULL,
  tracking VARCHAR(80) NULL,
  estado envio_estado NOT NULL DEFAULT 'preparando',
  costo DECIMAL(12,2) NOT NULL DEFAULT 0,
  fecha_estimada DATE NULL,
  entregado_en TIMESTAMPTZ NULL,
  evidencia_url VARCHAR(255) NULL
);

CREATE TABLE devolucion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero VARCHAR(20) NOT NULL UNIQUE,
  pedido_id BIGINT NOT NULL,
  cliente_id INT NULL,
  motivo devolucion_motivo NOT NULL,
  detalle VARCHAR(255) NULL,
  estado devolucion_estado NOT NULL DEFAULT 'solicitada',
  monto_reembolso DECIMAL(12,2) NOT NULL DEFAULT 0,
  usuario_gestiona_id INT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  cerrado_en TIMESTAMPTZ NULL
);

CREATE TABLE devolucion_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  devolucion_id BIGINT NOT NULL,
  pedido_detalle_id BIGINT NOT NULL,
  variante_id INT NOT NULL,
  cantidad INT NOT NULL,
  estado_prenda devolucion_detalle_estado_prenda NOT NULL DEFAULT 'nueva',
  reingresa_stock BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE avatar (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id INT NOT NULL UNIQUE,
  tipo_cuerpo avatar_tipo_cuerpo NULL,
  -- proporciones normalizadas que consume el render del avatar en el navegador
  parametros JSONB NOT NULL,
  url_render VARCHAR(255) NULL,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE prueba_virtual (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id INT NULL,
  session_token VARCHAR(64) NULL,          -- permite probar sin estar logueado
  variante_id INT NOT NULL,
  modo prueba_virtual_modo NOT NULL,
  talla_recomendada_id INT NULL,
  -- que tan bien le queda segun las medidas: -2 muy chica ... +2 muy grande
  ajuste SMALLINT NULL,
  captura_url VARCHAR(255) NULL,
  duracion_seg INT NULL,
  convirtio_en_compra BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE resena (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id INT NOT NULL,
  cliente_id INT NOT NULL,
  pedido_id BIGINT NULL,
  calificacion SMALLINT NOT NULL,
  comentario VARCHAR(500) NULL,
  talla_comprada_id INT NULL,
  ajuste_real resena_ajuste_real NULL,
  aprobado BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_res_calif CHECK (calificacion BETWEEN 1 AND 5),
  CONSTRAINT uq_resena UNIQUE (producto_id, cliente_id, pedido_id)
);

CREATE TABLE conversacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INT NULL,                    -- NULL = visitante anonimo
  session_token VARCHAR(64) NOT NULL,
  canal conversacion_canal NOT NULL DEFAULT 'web',
  -- asistente_compra = cliente pregunta por ropa; reporte = staff pide datos
  tipo conversacion_tipo NOT NULL DEFAULT 'asistente_compra',
  titulo VARCHAR(150) NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE mensaje (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversacion_id BIGINT NOT NULL,
  rol mensaje_rol NOT NULL,
  contenido TEXT NULL,
  -- cuando el modelo llama a una funcion del backend queda registrado aqui
  herramienta VARCHAR(60) NULL,
  payload JSONB NULL,
  -- entrada por voz: se guarda la transcripcion y el audio original
  audio_url VARCHAR(255) NULL,
  tokens_entrada INT NULL,
  tokens_salida INT NULL,
  latencia_ms INT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE plantilla_reporte (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(60) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  descripcion VARCHAR(255) NULL,
  -- SQL con marcadores :param, validado por el backend antes de ejecutar
  sql_plantilla TEXT NOT NULL,
  -- esquema JSON de los parametros que el modelo debe completar
  parametros JSONB NOT NULL,
  permiso_id INT NULL,
  visual_default plantilla_reporte_visual_default NOT NULL DEFAULT 'tabla',
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE consulta_reporte (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversacion_id BIGINT NULL,
  usuario_id INT NOT NULL,
  plantilla_id INT NULL,
  pregunta TEXT NOT NULL,
  entrada consulta_reporte_entrada NOT NULL DEFAULT 'texto',
  parametros JSONB NULL,
  sql_ejecutado TEXT NULL,
  filas INT NULL,
  exito BOOLEAN NOT NULL DEFAULT TRUE,
  error VARCHAR(255) NULL,
  duracion_ms INT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE sync_operacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dispositivo_id INT NOT NULL,
  usuario_id INT NULL,
  idempotency_key VARCHAR(36) NOT NULL UNIQUE,
  entidad VARCHAR(40) NOT NULL,    -- pedido, pago, inventario, carrito
  operacion sync_operacion_operacion NOT NULL,
  payload JSONB NOT NULL,
  estado sync_operacion_estado NOT NULL DEFAULT 'pendiente',
  resultado JSONB NULL,
  error VARCHAR(255) NULL,
  creado_en_cliente TIMESTAMPTZ NOT NULL,
  recibido_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  procesado_en TIMESTAMPTZ NULL
);

CREATE TABLE notificacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INT NOT NULL,
  titulo VARCHAR(120) NOT NULL,
  mensaje VARCHAR(255) NOT NULL,
  tipo notificacion_tipo NOT NULL,
  url VARCHAR(255) NULL,
  leida BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- 3. CLAVES AJENAS (91)
-- ============================================================================

ALTER TABLE ciudad ADD CONSTRAINT fk_ciudad_depto FOREIGN KEY (departamento_id) REFERENCES departamento(id);
ALTER TABLE sucursal ADD CONSTRAINT fk_sucursal_ciudad FOREIGN KEY (ciudad_id) REFERENCES ciudad(id);
ALTER TABLE almacen ADD CONSTRAINT fk_almacen_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursal(id);
ALTER TABLE rol_permiso ADD CONSTRAINT fk_rp_rol FOREIGN KEY (rol_id) REFERENCES rol(id)     ON DELETE CASCADE;
ALTER TABLE rol_permiso ADD CONSTRAINT fk_rp_permiso FOREIGN KEY (permiso_id) REFERENCES permiso(id) ON DELETE CASCADE;
ALTER TABLE usuario ADD CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id) REFERENCES rol(id);
ALTER TABLE usuario ADD CONSTRAINT fk_usuario_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursal(id);
ALTER TABLE dispositivo ADD CONSTRAINT fk_dispositivo_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id);
ALTER TABLE sesion ADD CONSTRAINT fk_sesion_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE;
ALTER TABLE sesion ADD CONSTRAINT fk_sesion_dispositivo FOREIGN KEY (dispositivo_id) REFERENCES dispositivo(id);
ALTER TABLE bitacora ADD CONSTRAINT fk_bitacora_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id);
ALTER TABLE cliente ADD CONSTRAINT fk_cliente_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE;
ALTER TABLE direccion_cliente ADD CONSTRAINT fk_dir_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(usuario_id) ON DELETE CASCADE;
ALTER TABLE direccion_cliente ADD CONSTRAINT fk_dir_ciudad FOREIGN KEY (ciudad_id) REFERENCES ciudad(id);
ALTER TABLE medida_cliente ADD CONSTRAINT fk_medida_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(usuario_id) ON DELETE CASCADE;
ALTER TABLE categoria ADD CONSTRAINT fk_categoria_padre FOREIGN KEY (padre_id) REFERENCES categoria(id);
ALTER TABLE producto ADD CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id) REFERENCES categoria(id);
ALTER TABLE producto ADD CONSTRAINT fk_producto_marca FOREIGN KEY (marca_id) REFERENCES marca(id);
ALTER TABLE producto_imagen ADD CONSTRAINT fk_img_producto FOREIGN KEY (producto_id) REFERENCES producto(id) ON DELETE CASCADE;
ALTER TABLE producto_imagen ADD CONSTRAINT fk_img_color FOREIGN KEY (color_id) REFERENCES color(id);
ALTER TABLE producto_prenda_3d ADD CONSTRAINT fk_p3d_producto FOREIGN KEY (producto_id) REFERENCES producto(id) ON DELETE CASCADE;
ALTER TABLE producto_prenda_3d ADD CONSTRAINT fk_p3d_color FOREIGN KEY (color_id) REFERENCES color(id);
ALTER TABLE variante ADD CONSTRAINT fk_var_producto FOREIGN KEY (producto_id) REFERENCES producto(id) ON DELETE CASCADE;
ALTER TABLE variante ADD CONSTRAINT fk_var_talla FOREIGN KEY (talla_id) REFERENCES talla(id);
ALTER TABLE variante ADD CONSTRAINT fk_var_color FOREIGN KEY (color_id) REFERENCES color(id);
ALTER TABLE escala_precio ADD CONSTRAINT fk_escala_variante FOREIGN KEY (variante_id) REFERENCES variante(id) ON DELETE CASCADE;
ALTER TABLE guia_talla ADD CONSTRAINT fk_guia_categoria FOREIGN KEY (categoria_id) REFERENCES categoria(id) ON DELETE CASCADE;
ALTER TABLE guia_talla ADD CONSTRAINT fk_guia_talla FOREIGN KEY (talla_id) REFERENCES talla(id);
ALTER TABLE inventario ADD CONSTRAINT fk_inv_variante FOREIGN KEY (variante_id) REFERENCES variante(id) ON DELETE CASCADE;
ALTER TABLE inventario ADD CONSTRAINT fk_inv_almacen FOREIGN KEY (almacen_id) REFERENCES almacen(id);
ALTER TABLE movimiento_inventario ADD CONSTRAINT fk_mov_variante FOREIGN KEY (variante_id) REFERENCES variante(id);
ALTER TABLE movimiento_inventario ADD CONSTRAINT fk_mov_almacen FOREIGN KEY (almacen_id) REFERENCES almacen(id);
ALTER TABLE movimiento_inventario ADD CONSTRAINT fk_mov_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id);
ALTER TABLE transferencia ADD CONSTRAINT fk_tr_origen FOREIGN KEY (almacen_origen_id) REFERENCES almacen(id);
ALTER TABLE transferencia ADD CONSTRAINT fk_tr_destino FOREIGN KEY (almacen_destino_id) REFERENCES almacen(id);
ALTER TABLE transferencia ADD CONSTRAINT fk_tr_solicita FOREIGN KEY (usuario_solicita_id) REFERENCES usuario(id);
ALTER TABLE transferencia ADD CONSTRAINT fk_tr_aprueba FOREIGN KEY (usuario_aprueba_id) REFERENCES usuario(id);
ALTER TABLE transferencia_detalle ADD CONSTRAINT fk_trd_transferencia FOREIGN KEY (transferencia_id) REFERENCES transferencia(id) ON DELETE CASCADE;
ALTER TABLE transferencia_detalle ADD CONSTRAINT fk_trd_variante FOREIGN KEY (variante_id) REFERENCES variante(id);
ALTER TABLE compra ADD CONSTRAINT fk_compra_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedor(id);
ALTER TABLE compra ADD CONSTRAINT fk_compra_almacen FOREIGN KEY (almacen_id) REFERENCES almacen(id);
ALTER TABLE compra ADD CONSTRAINT fk_compra_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id);
ALTER TABLE compra_detalle ADD CONSTRAINT fk_cd_compra FOREIGN KEY (compra_id) REFERENCES compra(id) ON DELETE CASCADE;
ALTER TABLE compra_detalle ADD CONSTRAINT fk_cd_variante FOREIGN KEY (variante_id) REFERENCES variante(id);
ALTER TABLE promocion ADD CONSTRAINT fk_promo_campania FOREIGN KEY (campania_id) REFERENCES campania(id);
ALTER TABLE carrito ADD CONSTRAINT fk_carrito_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(usuario_id) ON DELETE CASCADE;
ALTER TABLE carrito_item ADD CONSTRAINT fk_ci_carrito FOREIGN KEY (carrito_id) REFERENCES carrito(id) ON DELETE CASCADE;
ALTER TABLE carrito_item ADD CONSTRAINT fk_ci_variante FOREIGN KEY (variante_id) REFERENCES variante(id);
ALTER TABLE pedido ADD CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(usuario_id);
ALTER TABLE pedido ADD CONSTRAINT fk_pedido_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursal(id);
ALTER TABLE pedido ADD CONSTRAINT fk_pedido_almacen FOREIGN KEY (almacen_id) REFERENCES almacen(id);
ALTER TABLE pedido ADD CONSTRAINT fk_pedido_vendedor FOREIGN KEY (vendedor_id) REFERENCES usuario(id);
ALTER TABLE pedido ADD CONSTRAINT fk_pedido_direccion FOREIGN KEY (direccion_id) REFERENCES direccion_cliente(id);
ALTER TABLE pedido ADD CONSTRAINT fk_pedido_promocion FOREIGN KEY (promocion_id) REFERENCES promocion(id);
ALTER TABLE pedido_detalle ADD CONSTRAINT fk_pd_pedido FOREIGN KEY (pedido_id) REFERENCES pedido(id) ON DELETE CASCADE;
ALTER TABLE pedido_detalle ADD CONSTRAINT fk_pd_variante FOREIGN KEY (variante_id) REFERENCES variante(id);
ALTER TABLE pedido_historial ADD CONSTRAINT fk_ph_pedido FOREIGN KEY (pedido_id) REFERENCES pedido(id) ON DELETE CASCADE;
ALTER TABLE pedido_historial ADD CONSTRAINT fk_ph_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id);
ALTER TABLE pago ADD CONSTRAINT fk_pago_pedido FOREIGN KEY (pedido_id) REFERENCES pedido(id) ON DELETE CASCADE;
ALTER TABLE pago ADD CONSTRAINT fk_pago_metodo FOREIGN KEY (metodo_pago_id) REFERENCES metodo_pago(id);
ALTER TABLE pago ADD CONSTRAINT fk_pago_usuario FOREIGN KEY (usuario_confirma_id) REFERENCES usuario(id);
ALTER TABLE caja ADD CONSTRAINT fk_caja_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursal(id);
ALTER TABLE caja ADD CONSTRAINT fk_caja_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id);
ALTER TABLE movimiento_caja ADD CONSTRAINT fk_mc_caja FOREIGN KEY (caja_id) REFERENCES caja(id) ON DELETE CASCADE;
ALTER TABLE movimiento_caja ADD CONSTRAINT fk_mc_pago FOREIGN KEY (pago_id) REFERENCES pago(id);
ALTER TABLE envio ADD CONSTRAINT fk_envio_pedido FOREIGN KEY (pedido_id) REFERENCES pedido(id) ON DELETE CASCADE;
ALTER TABLE envio ADD CONSTRAINT fk_envio_direccion FOREIGN KEY (direccion_id) REFERENCES direccion_cliente(id);
ALTER TABLE envio ADD CONSTRAINT fk_envio_repartidor FOREIGN KEY (repartidor_id) REFERENCES usuario(id);
ALTER TABLE devolucion ADD CONSTRAINT fk_dev_pedido FOREIGN KEY (pedido_id) REFERENCES pedido(id);
ALTER TABLE devolucion ADD CONSTRAINT fk_dev_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(usuario_id);
ALTER TABLE devolucion ADD CONSTRAINT fk_dev_usuario FOREIGN KEY (usuario_gestiona_id) REFERENCES usuario(id);
ALTER TABLE devolucion_detalle ADD CONSTRAINT fk_dd_devolucion FOREIGN KEY (devolucion_id) REFERENCES devolucion(id) ON DELETE CASCADE;
ALTER TABLE devolucion_detalle ADD CONSTRAINT fk_dd_detalle FOREIGN KEY (pedido_detalle_id) REFERENCES pedido_detalle(id);
ALTER TABLE devolucion_detalle ADD CONSTRAINT fk_dd_variante FOREIGN KEY (variante_id) REFERENCES variante(id);
ALTER TABLE avatar ADD CONSTRAINT fk_avatar_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(usuario_id) ON DELETE CASCADE;
ALTER TABLE prueba_virtual ADD CONSTRAINT fk_pv_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(usuario_id);
ALTER TABLE prueba_virtual ADD CONSTRAINT fk_pv_variante FOREIGN KEY (variante_id) REFERENCES variante(id);
ALTER TABLE prueba_virtual ADD CONSTRAINT fk_pv_talla FOREIGN KEY (talla_recomendada_id) REFERENCES talla(id);
ALTER TABLE resena ADD CONSTRAINT fk_res_producto FOREIGN KEY (producto_id) REFERENCES producto(id) ON DELETE CASCADE;
ALTER TABLE resena ADD CONSTRAINT fk_res_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(usuario_id);
ALTER TABLE resena ADD CONSTRAINT fk_res_pedido FOREIGN KEY (pedido_id) REFERENCES pedido(id);
ALTER TABLE resena ADD CONSTRAINT fk_res_talla FOREIGN KEY (talla_comprada_id) REFERENCES talla(id);
ALTER TABLE conversacion ADD CONSTRAINT fk_conv_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id);
ALTER TABLE mensaje ADD CONSTRAINT fk_msg_conversacion FOREIGN KEY (conversacion_id) REFERENCES conversacion(id) ON DELETE CASCADE;
ALTER TABLE plantilla_reporte ADD CONSTRAINT fk_plantilla_permiso FOREIGN KEY (permiso_id) REFERENCES permiso(id);
ALTER TABLE consulta_reporte ADD CONSTRAINT fk_cr_conversacion FOREIGN KEY (conversacion_id) REFERENCES conversacion(id);
ALTER TABLE consulta_reporte ADD CONSTRAINT fk_cr_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id);
ALTER TABLE consulta_reporte ADD CONSTRAINT fk_cr_plantilla FOREIGN KEY (plantilla_id) REFERENCES plantilla_reporte(id);
ALTER TABLE sync_operacion ADD CONSTRAINT fk_sync_dispositivo FOREIGN KEY (dispositivo_id) REFERENCES dispositivo(id);
ALTER TABLE sync_operacion ADD CONSTRAINT fk_sync_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id);
ALTER TABLE notificacion ADD CONSTRAINT fk_notif_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE;

-- ============================================================================
-- 4. INDICES (31)
-- ============================================================================

CREATE INDEX idx_sucursal_ciudad ON sucursal (ciudad_id);
CREATE INDEX idx_almacen_sucursal ON almacen (sucursal_id);
CREATE INDEX idx_usuario_rol ON usuario (rol_id);
CREATE INDEX idx_usuario_sucursal ON usuario (sucursal_id);
CREATE INDEX idx_sesion_usuario ON sesion (usuario_id);
CREATE INDEX idx_bitacora_usuario ON bitacora (usuario_id);
CREATE INDEX idx_bitacora_fecha ON bitacora (creado_en);
CREATE INDEX idx_bitacora_modulo ON bitacora (modulo, entidad, entidad_id);
CREATE INDEX idx_dir_cliente ON direccion_cliente (cliente_id);
CREATE INDEX idx_categoria_padre ON categoria (padre_id);
CREATE INDEX idx_producto_categoria ON producto (categoria_id);
CREATE INDEX ft_producto ON producto USING GIN (to_tsvector('spanish', coalesce(nombre, '') || ' ' || coalesce(descripcion, '') || ' ' || coalesce(material, '')));
CREATE INDEX idx_img_producto ON producto_imagen (producto_id);
CREATE INDEX idx_var_producto ON variante (producto_id);
CREATE INDEX idx_inv_almacen ON inventario (almacen_id);
CREATE INDEX idx_mov_variante ON movimiento_inventario (variante_id, creado_en);
CREATE INDEX idx_mov_ref ON movimiento_inventario (referencia_tipo, referencia_id);
CREATE INDEX idx_pedido_fecha ON pedido (creado_en);
CREATE INDEX idx_pedido_sucursal_fecha ON pedido (sucursal_id, creado_en);
CREATE INDEX idx_pedido_estado ON pedido (estado);
CREATE INDEX idx_pedido_cliente ON pedido (cliente_id);
CREATE INDEX idx_pd_pedido ON pedido_detalle (pedido_id);
CREATE INDEX idx_pd_variante ON pedido_detalle (variante_id);
CREATE INDEX idx_pago_pedido ON pago (pedido_id);
CREATE INDEX idx_pv_variante ON prueba_virtual (variante_id);
CREATE INDEX idx_pv_fecha ON prueba_virtual (creado_en);
CREATE INDEX idx_conv_session ON conversacion (session_token);
CREATE INDEX idx_msg_conv ON mensaje (conversacion_id, creado_en);
CREATE INDEX idx_cr_usuario ON consulta_reporte (usuario_id, creado_en);
CREATE INDEX idx_sync_estado ON sync_operacion (estado, recibido_en);
CREATE INDEX idx_notif_usuario ON notificacion (usuario_id, leida);

-- ============================================================================
-- 5. DISPARADORES DE actualizado_en (8)
-- ============================================================================

CREATE TRIGGER tg_usuario_actualizado BEFORE UPDATE ON usuario
  FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

CREATE TRIGGER tg_medida_cliente_actualizado BEFORE UPDATE ON medida_cliente
  FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

CREATE TRIGGER tg_producto_actualizado BEFORE UPDATE ON producto
  FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

CREATE TRIGGER tg_inventario_actualizado BEFORE UPDATE ON inventario
  FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

CREATE TRIGGER tg_carrito_actualizado BEFORE UPDATE ON carrito
  FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

CREATE TRIGGER tg_pedido_actualizado BEFORE UPDATE ON pedido
  FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

CREATE TRIGGER tg_avatar_actualizado BEFORE UPDATE ON avatar
  FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

CREATE TRIGGER tg_conversacion_actualizado BEFORE UPDATE ON conversacion
  FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

-- ============================================================================
-- 6. VISTAS DE APOYO PARA REPORTES (2)
-- ============================================================================

CREATE OR REPLACE VIEW v_stock_sucursal AS
SELECT s.id  AS sucursal_id, s.nombre AS sucursal,
       v.id  AS variante_id, v.sku,
       p.id  AS producto_id, p.nombre AS producto,
       t.nombre AS talla, c.nombre AS color,
       SUM(i.stock)           AS stock_total,
       SUM(i.stock_reservado) AS reservado,
       SUM(i.stock - i.stock_reservado) AS disponible
FROM inventario i
JOIN almacen  a ON a.id = i.almacen_id
JOIN sucursal s ON s.id = a.sucursal_id
JOIN variante v ON v.id = i.variante_id
JOIN producto p ON p.id = v.producto_id
JOIN talla    t ON t.id = v.talla_id
JOIN color    c ON c.id = v.color_id
GROUP BY s.id, s.nombre, v.id, v.sku, p.id, p.nombre, t.nombre, c.nombre;

CREATE OR REPLACE VIEW v_ventas_detalle AS
SELECT pe.id AS pedido_id, pe.numero, pe.creado_en, pe.canal, pe.modalidad, pe.estado,
       pe.sucursal_id, s.nombre AS sucursal, d.nombre AS departamento,
       pe.vendedor_id, pe.cliente_id,
       pd.variante_id, v.sku, pr.id AS producto_id, pr.nombre AS producto,
       cat.id AS categoria_id, cat.nombre AS categoria,
       pd.cantidad, pd.precio_unitario, pd.subtotal
FROM pedido pe
JOIN pedido_detalle pd ON pd.pedido_id = pe.id
JOIN variante  v   ON v.id  = pd.variante_id
JOIN producto  pr  ON pr.id = v.producto_id
JOIN categoria cat ON cat.id = pr.categoria_id
JOIN sucursal  s   ON s.id  = pe.sucursal_id
JOIN ciudad    ci  ON ci.id = s.ciudad_id
JOIN departamento d ON d.id = ci.departamento_id
WHERE pe.estado NOT IN ('cancelado','pendiente');
